{
 "title": "RPS_Latency_Errors",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"application\", uri!=\"/actuator/prometheus\"}[10s])) by (uri, method)"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"application\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_server_requests_seconds_count{job=\"application\"}[1m]))"
    }
   ]
  },
  {
   "title": "LATENCY 50-95-99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_server_requests_seconds_bucket[60s])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket[60s])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket[60s])) by (le))"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"application\", status=~\"4.+|5.+\"}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"application\", status=~\"4.+|5.+\"}[1m]))"
    }
   ]
  }
 ]
}