apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service
  labels:
    release: prom
spec:
  endpoints:
    - port: http
      path: '/actuator/prometheus'
      interval: 5s
  jobLabel: prom
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: app-service
      release: prom